"""English text of the game's alert, help and warning messages. Generated.

From the game's ``data/language/{base-language,fullgame,d11}.txt`` (inside
``main.dat``): keys whose name contains ``staffalert``, ``warning`` or starts
with ``help_``. Used to show ``StaffAlert`` / ``NewSpeechAdded`` keys as text.
"""

TEXT: dict[str, str] = {
    "codex_nitgs_authwarning": "Important: If you have recently changed your Name in the Game entry, it will need to be authorised before it will appear in the list.",
    "codex_options_staffalertscaption": "Staff Alerts",
    "codex_workshop_update_warning": "Updating Published Prison",
    "codex_workshop_update_warning_msg": "Updating this Published Prison will override the published prison with the currently loaded prison. This will delete the published prison, permanently replacing it with the prison you are currently playing. This action can not be undone.\\n\\nAre you sure you wish to proceed?",
    "d11_gangBulkIntake_staffAlert": "Gang Member Intake bus is arriving",
    "d11_staffalert_details_AdvancedFarming01": "The Automatic Planting option can be turned on or off via the Policy menu.",
    "d11_staffalert_details_AdvancedFarming02": "After being unlocked, this option can be found within the Logistics menu.",
    "d11_staffalert_details_AdvancedFarming03": 'Researching "Farming" will unlock the Compost Bin and the 2 Fertilizer types.',
    "d11_staffalert_details_BasicFarming01": "Each Farming Room needs to be outdoors and must have shed object placed inside.",
    "d11_staffalert_details_BasicFarming02": "Farmers will work as teachers to prisoners, for the Farming Training program.",
    "d11_staffalert_details_BasicFarming03": "Although Fruit Trees are expensive and have long growth times, they have much higher yields than any other crop type.",
    "d11_staffalert_details_CELLS01": "We can house *A more prisoners.",
    "d11_staffalert_details_CELLS01Z": "We have *A free *B cells.",
    "d11_staffalert_details_CELLS01a": "We can house *A more minimum security prisoners.",
    "d11_staffalert_details_CELLS01b": "We can house *A more medium security prisoners.",
    "d11_staffalert_details_CELLS01c": "We can house *A more maximum security prisoners.",
    "d11_staffalert_details_CELLS01d": "We can house *A more super max security prisoners.",
    "d11_staffalert_details_CELLS01e": "We can house *A more death row prisoners.",
    "d11_staffalert_details_CELLS01f": "We can house *A more protective security prisoners.",
    "d11_staffalert_details_CONTRABAND01a": "The supply of weapons is at *A.",
    "d11_staffalert_details_CONTRABAND01b": "The supply of tools is at *A.",
    "d11_staffalert_details_CONTRABAND02": "The supply of narcotics is at *A.",
    "d11_staffalert_details_CONTRABAND03": "*A items of contraband found in the last 7 days.",
    "d11_staffalert_details_CalamityHeatwave01": "There's a few issues that could arise during a heatwave. Metal can become extremely hot, so be careful with any metallic objects and doors. Also, make sure to keep your prisoners and staff hydrated as they might become sluggish.",
    "d11_staffalert_details_DEATHROW01": "Adding a Death Row to your prison will allow you to accept high value Death Row inmates.",
    "d11_staffalert_details_DOCTOR01": "We need to hire some doctors to treat our wounded prisoners and guards.",
    "d11_staffalert_details_DeepFreeze01": "Whilst experiencing this severe cold, many parts of the prison could become frosty or completely frozen. Prisoners will also have a higher chance of becoming ill and in extreme cases become frozen themselves.",
    "d11_staffalert_details_GreenEnergy01": "Green Energy must flow via the direction following the arrow marks displayed on both sides of the Transformer.",
    "d11_staffalert_details_GreenEnergy02": "Similar to Capacitors and Power Stations, Battery objects can only be placed adjacent to a Transformer.",
    "d11_staffalert_details_GreenEnergy03": "Power Export Metres must be wired up to a Transformer, with attached Batteries, to operate correctly.",
    "d11_staffalert_details_HOLDINGCELL01": "*A prisoners are currently without their own cell.",
    "d11_staffalert_details_INFORMANTS01": "The inmates strongly suspect *A is an informant.",
    "d11_staffalert_details_LightningStorm01": "Storms can cause all kinds of issues for your prison. They can interfere with electrical items, cause damage and fires if struck by lightning, destroy full areas of your prison and can even electrocute people.",
    "d11_staffalert_details_MONEY01": "The prison only has *A left in the bank.",
    "d11_staffalert_details_MysteryCrate": "Looks like an item meant for a different facility fell off a truck passing by, since that facility will be getting a full refund for this mistake this means we've gotten a free goodie. I wonder what's inside.",
    "d11_staffalert_details_NEEDS01": "*A prisoners urgently need the toilet.",
    "d11_staffalert_details_NEEDS02": "*A prisoners urgently need the toilet.",
    "d11_staffalert_details_NEEDS03": "*A prisoners urgently need sleep.",
    "d11_staffalert_details_NEEDS04a": "*A prisoners are incredibly hungry.",
    "d11_staffalert_details_NEEDS04b": "Build more Kitchens.",
    "d11_staffalert_details_NEEDS04c": "Hire more Cooks.",
    "d11_staffalert_details_NEEDS04d": "Add more 'Meal Time' slots to your regime.",
    "d11_staffalert_details_NEEDS05": "*A prisoners are desperate to contact their families.",
    "d11_staffalert_details_NEEDS06a": "Hire more Janitors.",
    "d11_staffalert_details_NEEDS06b": "Build more Cleaning Cupboards.",
    "d11_staffalert_details_NEEDS06c": "Assign prisoners to work from the Cleaning Cupboards.",
    "d11_staffalert_details_NEEDS07": "*A prisoners fear for their lives.",
    "d11_staffalert_details_NEEDS08": "*A prisoners need to improve their cleanliness.",
    "d11_staffalert_details_NEEDS09": "*A prisoners need to improve their fitness.",
    "d11_staffalert_details_NEEDS10": "*A prisoners need recreational activities to stay calm.",
    "d11_staffalert_details_NEEDS11": "*A prisoners are complaining about a lack of places to sit during Free-Time.",
    "d11_staffalert_details_NEEDS12": "*A prisoners want somewhere to be alone.",
    "d11_staffalert_details_NEEDS13": "*A prisoners want more Free Time.",
    "d11_staffalert_details_NEEDS14a": "*A prisoners need clean clothes.",
    "d11_staffalert_details_NEEDS14b": "Build a Laundry room.",
    "d11_staffalert_details_NEEDS14c": "Build a Laundry Machine.",
    "d11_staffalert_details_NEEDS14d": "Build a Laundry Basket.",
    "d11_staffalert_details_NEEDS15": "*A prisoners are addicted to drugs.",
    "d11_staffalert_details_NEEDS16": "*A prisoners have a drinking problem.",
    "d11_staffalert_details_NEEDS18": "*A prisoners want spiritual guidance.",
    "d11_staffalert_details_NEEDS19": "*A prisoners lack basic literary skills.",
    "d11_staffalert_details_OBJECTS01": "The prison does not have a sprinkler system set up.",
    "d11_staffalert_details_OBJECTS02": "More Bins required.",
    "d11_staffalert_details_OBJECTS03": "More CCTV Cameras required.",
    "d11_staffalert_details_OBJECTS04": "A Door Control system and Door Servos required.",
    "d11_staffalert_details_POWER01": "Connect all objects with flashing lightning bolt icons on them to a Power Station.",
    "d11_staffalert_details_POWER02": "The output of a Power Station in your prison is at *A.",
    "d11_staffalert_details_PRISONERS02": "The prisoners outnumber your guards *A:*B.",
    "d11_staffalert_details_PRISONERS03": "*A prisoners are currently living in cells which don't meet their entitlement.",
    "d11_staffalert_details_ROOMS01": "Make sure rooms with flashing red exclamation mark icons meet the full listed criteria.",
    "d11_staffalert_details_RatInfestationLevel01": "Although a dirty prison makes your inmates unhappy, it makes rats extremely happy. Be careful of them scurrying around, as they can make your prisoners sick, help themselves to your stored food, and chew their way through cables and fences.",
    "d11_staffalert_details_STAFF01": "*A staff members are currently exhausted.",
    "d11_staffalert_details_WATER01": "Connect all objects with flashing water drop icons on them to the water pump.",
    "d11_staffalert_details_WeatherDetected": "Incoming weather event detected...",
    "d11_staffalert_details_granterror": "Due to an administrative error, our completion bonus has been doubled!",
    "d11_staffalert_hint_AdvancedFarming01": "This behaviour matches that of the Forestry.",
    "d11_staffalert_hint_AdvancedFarming02": "Rooms related to growing, utilising, or storing food can be linked to each other, providing micro-management over ingredient distribution.",
    "d11_staffalert_hint_AdvancedFarming03": "The Compost Bin will turn food and plant waste along with other substances into Compost Fertilizer for free.",
    "d11_staffalert_hint_BasicFarming01": "Unlike Vegetables and Fruit, Cereal crops can only be sold as an export.",
    "d11_staffalert_hint_BasicFarming02": "Farmers will also perform all Gardening jobs within their farming areas.",
    "d11_staffalert_hint_BasicFarming03": "Fruit Trees provide the most efficient food supply when grown in large quantities.",
    "d11_staffalert_hint_CELLS01": "Taking in more prisoners gives us a nice up front cash bonus, it also means we get more money from the state every day. We should always run at full capacity if possible!",
    "d11_staffalert_hint_CONTRABAND01": "Prisoners have easy access to tools and weapons, which is very dangerous. Place metal detectors near the sources of contraband or order a prison-wide Shakedown.",
    "d11_staffalert_hint_CONTRABAND02": "Prisoners have easy access to narcotics, which is very dangerous. Hire Dog Handlers and have them patrol the cell blocks or order a prison-wide Shakedown.",
    "d11_staffalert_hint_CONTRABAND03": "Check the contraband intelligence report I filed to locate the sources of contraband over the last 7 days and enact measures to close them off.",
    "d11_staffalert_hint_CalamityHeatwave01": "A fire with a high wind could prove itself a catastrophe, make sure to prevent it and make preparations.",
    "d11_staffalert_hint_DEATHROW01": "Adding a Death Row to the Prison is risky as the execution needs to be handled very carefully so we meet all of the legal requirements... But, we could make lot of money, so it may be worth the risk!",
    "d11_staffalert_hint_DOCTOR01": "We can't treat anyone in the Infirmary unless you hire some Doctors. Doctors can use the infirmary to treat any injuries that occur to staff or prisoners.",
    "d11_staffalert_hint_DeepFreeze01": "It's always best to have grit boxes available, have the utility items in your prison properly insulated, and to have a good level of medical support on hand.",
    "d11_staffalert_hint_GreenEnergy01": "If raw green power is directly linked to any appliance it will cause a blackout.",
    "d11_staffalert_hint_GreenEnergy02": "Batteries will store any unused power for emergency use or for Power Exporting.",
    "d11_staffalert_hint_GreenEnergy03": "Batteries can be charged by any power source connected to a Transformer, even Power Stations.",
    "d11_staffalert_hint_HOLDINGCELL01": "It's too dangerous to leave this many prisoners in the Holding Cells long-term. You must build more Cells to house them as soon as possible or they may start a riot!",
    "d11_staffalert_hint_INFORMANTS01": "Our Informant will not last long in here without our protection, I suggest changing their security level to 'Protective Custody' and moving them out of general population.",
    "d11_staffalert_hint_LightningStorm01": "You'll need to secure your prison and install lightning rods to minimise damage as much as possible during these storms.",
    "d11_staffalert_hint_MONEY01": "The prison is running out of money, may I suggest we take in more prisoners to increase our daily income or meet the conditions for a new grant for a large cash injection.",
    "d11_staffalert_hint_NEEDS01": "Prisoners need access to toilets, consider adding more toilets to your prison or increasing your allocation of Free Time.",
    "d11_staffalert_hint_NEEDS02": "Prisoners need access to toilets, consider adding more toilets to your prison or increasing your allocation of Free Time.",
    "d11_staffalert_hint_NEEDS03": "Prisoners need to sleep to stay happy. They will do this during the allocated Sleep periods or during Free Time.",
    "d11_staffalert_hint_NEEDS04": "Prisoners will get hungry over time, make sure there is enough room in the canteen and enough time allocated for eating so that everyone can be fed.",
    "d11_staffalert_hint_NEEDS05": "Prisoners can become angry if they are not allowed to communicate with their families. Build a Visitation Room, a Mail Room or Phone Booths to hold off the prison blues.",
    "d11_staffalert_hint_NEEDS06": "The prison is very dirty and it is making your inmates very unhappy, find a way to clean up as quickly as you can before they become angry.",
    "d11_staffalert_hint_NEEDS07": "If the danger level of your prison is too high many prisoners will start to feel unsafe and scared. Lower your danger level by catering to your prisoners other needs.",
    "d11_staffalert_hint_NEEDS08": "Hygiene is important in every day life, in prison it's essential. Make sure your prisoners have plenty of time to catch a shower.",
    "d11_staffalert_hint_NEEDS09": "Exercise keeps your prisoners fit, healthy and happy. Make sure they have easy access to weight benches.",
    "d11_staffalert_hint_NEEDS10": "Help break up the day to day monotony by giving your prisoners access to recreational items such as Pool Tables, Radios and TV's.",
    "d11_staffalert_hint_NEEDS11": "Downtime is important for everyone, but in prison, it can be hard to find. Giving your prisoners benches and sofas to sit on will help them to relax.",
    "d11_staffalert_hint_NEEDS12": "Sometimes, prisoners just need some alone time, however “it's not you, it's me” doesn't tend to go down too well in prisons. Make sure prisoners have access to their own cell.",
    "d11_staffalert_hint_NEEDS13": "Prisoners all want one thing. To not be in prison. While we can't give them that, we can make their stay more pleasant with plenty of Free Time.",
    "d11_staffalert_hint_NEEDS14": "A fresh and clean uniform can make a big difference to a prisoner's quality of life. A Laundry Service is essential to catering to your prisoners 'Clothing' need.",
    "d11_staffalert_hint_NEEDS15": "Some inmates enter the prison with drug habits. If they can't get over their addiction they start to get angry, or they may start to deal in contraband to get their fix. Use reform programs to help their recovery.",
    "d11_staffalert_hint_NEEDS16": "Some inmates enter the prison with an addiction to alcohol. If they can't get over their addiction they start to get angry, or they may start to deal in contraband to get their fix. Use reform programs to help their recovery.",
    "d11_staffalert_hint_NEEDS18": "Attending spiritual guidance programs will have a calming effect on your prisoners, they will also spread this calm to other prisoners.",
    "d11_staffalert_hint_NEEDS19": "A reader lives a thousand lives before he dies, the man who never reads lives only one. Let your prisoners 'escape' into a good book by giving them access to a library.",
    "d11_staffalert_hint_OBJECTS01": "At the moment we are seriously unequipped to deal with a fire in the prison. We should install a sprinkler system as soon as possible.",
    "d11_staffalert_hint_OBJECTS02": "Bins allow us to store lots of rubbish before they need emptying, this means much fewer trips to the garbage area. Add bins to the kitchen and place them near metal detectors to increase efficiency.",
    "d11_staffalert_hint_OBJECTS03": "CCTV Cameras allow us to monitor areas of the prison even when no Guards are in the area. A single CCTV Monitor allows one Guard to view 8 different CCTV Cameras. They're a no brainer!",
    "d11_staffalert_hint_OBJECTS04": "Our guards currently have to spend most of their time opening jail doors for people, their time is too important for this! Install a Door Control system and one guard can open multiple doors remotely.",
    "d11_staffalert_hint_POWER01": "Certain objects need to be connected to a Power Station to work, use electrical cables to connect all objects with a flashing lightning bolt icon on them to a Power Station.",
    "d11_staffalert_hint_POWER02": "Our Power Station is seriously overloaded, add more capacitors to it or build a new one to share the load. Be careful though, Power Stations can't be connected together!",
    "d11_staffalert_hint_PRISONERS02": "It's not safe for your guards to be so heavily outnumbered by the prisoners, each guard can safely manage around 5 prisoners.",
    "d11_staffalert_hint_PRISONERS03": "All of our prisoners are entitled to a cell of a certain level of quality based on their behaviour. Improve the quality of a cell using the Logistics screen.",
    "d11_staffalert_hint_ROOMS01": "All rooms have certain requirements which you must meet, highlight rooms with flashing red exclamation mark icons to see which requirements you are not meeting.",
    "d11_staffalert_hint_RatInfestationLevel01": "To keep the rats away make sure that the prison is always clean and that any tunnels are removed as quickly as possible. Otherwise some kind of pest control would be needed.",
    "d11_staffalert_hint_STAFF01": "Your staff can't work effectively if they are exhausted, build them a staffroom so that they can relax or hire more staff as cover to ease the burden on them.",
    "d11_staffalert_hint_WATER01": "Certain objects need to be connected to a water pump to work, use water pipes to connect all objects with a flashing water drop icon on them to a water pump.",
    "d11_staffalert_summary_AdvancedFarming01": "Vegetable and cereal crops will by default be automatically bought again and re-planted after each harvest.",
    "d11_staffalert_summary_AdvancedFarming02": "Crop Distribution provides control over where prison-grown ingredients are moved after being harvested.",
    "d11_staffalert_summary_AdvancedFarming03": "Fertilizer can be applied to any area within Farming Rooms, it’s addition will improve the growth of crops.",
    "d11_staffalert_summary_ArmouryPlaced": "If you ever think your Guards need a little more shock-power you can enable a Prison Policy to have them equipped with Stun Batons",
    "d11_staffalert_summary_BasicFarming01": "Farming rooms allow for the planting of vegetables, fruit trees, and Cereals each, these crops can be either sold as exports or used for prisoner meals.",
    "d11_staffalert_summary_BasicFarming02": "The Farmer will handle all jobs related to farming, they are also required to teach inmates how to also perform these jobs.",
    "d11_staffalert_summary_BasicFarming03": "Unlike other crops, fruit trees will yield fruit continuously and as such the trees won't need replacing after every harvest.",
    "d11_staffalert_summary_CELLS01": "We have room to take in more prisoners.",
    "d11_staffalert_summary_CONTRABAND01": "Too many prisoners have access to tool and weapons.",
    "d11_staffalert_summary_CONTRABAND02": "Too many prisoners have access to narcotics.",
    "d11_staffalert_summary_CONTRABAND03": "There are high levels of contraband in the prison.",
    "d11_staffalert_summary_CalamityHeatwave01": "Is it getting hot in here? Make sure your prisoners and plants get enough water",
    "d11_staffalert_summary_DEATHROW01": "We could make some extra money if we added a Death Row to the prison.",
    "d11_staffalert_summary_DOCTOR01": "We should hire doctors to work in our Infirmary.",
    "d11_staffalert_summary_DeepFreeze01": "Be cautious of the potential hazards that come with the cold weather… Winter is coming.",
    "d11_staffalert_summary_GreenEnergy01": "All Green Energy sources need to be connected to a Transformer before their energy can be used.",
    "d11_staffalert_summary_GreenEnergy02": "Transformer objects are needed for both using green energy and for charging batteries.",
    "d11_staffalert_summary_GreenEnergy03": "Power Export Metres are used to send any unused power back to the regional grid for financial returns.",
    "d11_staffalert_summary_HOLDINGCELL01": "We have too many prisoners in our Holding Cells.",
    "d11_staffalert_summary_INFORMANTS01": "The inmates are highly suspicious of one of our informants.",
    "d11_staffalert_summary_LightningStorm01": "A storm's brewing, watch out for electrical issues and potential structural damage.",
    "d11_staffalert_summary_MONEY01": "We are running low on cash.",
    "d11_staffalert_summary_NEEDS01": "We should build some more toilets.",
    "d11_staffalert_summary_NEEDS02": "We should build some more toilets.",
    "d11_staffalert_summary_NEEDS03": "Our prisoners always look really tired.",
    "d11_staffalert_summary_NEEDS04": "Your prisoners are going hungry.",
    "d11_staffalert_summary_NEEDS05": "Our prisoners are missing their families.",
    "d11_staffalert_summary_NEEDS06": "The prison needs cleaning.",
    "d11_staffalert_summary_NEEDS07": "Our prisoners don't feel safe.",
    "d11_staffalert_summary_NEEDS08": "Oh, our prisoners look a little untidy.",
    "d11_staffalert_summary_NEEDS09": "Our prisoners are a little unfit.",
    "d11_staffalert_summary_NEEDS10": "Our prisoners are feeling a bit bored.",
    "d11_staffalert_summary_NEEDS11": "Prisoners are complaining about a lack of seats during Free Time.",
    "d11_staffalert_summary_NEEDS12": "Our prisoners want some privacy.",
    "d11_staffalert_summary_NEEDS13": "Our prisoners want more Free Time.",
    "d11_staffalert_summary_NEEDS14": "Hmm, our prisoners clothes are looking a bit...tatty.",
    "d11_staffalert_summary_NEEDS15": "Oh dear, it seems a lot of our prisoners have a drug problem.",
    "d11_staffalert_summary_NEEDS16": "It seems like a lot of our prisoners are quite partial to a drink.",
    "d11_staffalert_summary_NEEDS18": "A lot of our prisoners are seeking spiritual guidance.",
    "d11_staffalert_summary_NEEDS19": "Too many prisoners lack basic literacy skills.",
    "d11_staffalert_summary_OBJECTS01": "We are at risk if a fire breaks out.",
    "d11_staffalert_summary_OBJECTS02": "We need to buy some bins.",
    "d11_staffalert_summary_OBJECTS03": "We need to install CCTV Cameras.",
    "d11_staffalert_summary_OBJECTS04": "We should improve efficiency by installing a Door Control system.",
    "d11_staffalert_summary_POWER01": "Some areas of the Prison are without power.",
    "d11_staffalert_summary_POWER02": "Your Power Station is overloaded.",
    "d11_staffalert_summary_PRISONERS02": "We should hire more Guards.",
    "d11_staffalert_summary_PRISONERS03": "The general quality of our cells is too low.",
    "d11_staffalert_summary_ROOMS01": "Some of your rooms are invalid.",
    "d11_staffalert_summary_RatInfestationLevel01": "Rats, although cute, can bring disaster to your prison so be careful.",
    "d11_staffalert_summary_STAFF01": "Your staff are becoming exhausted.",
    "d11_staffalert_summary_TerritoryPlacement": "This room has been claimed by a Gang, and is too dangerous for our workmen. Evict them from the room.",
    "d11_staffalert_summary_WATER01": "Some areas of the Prison are without water.",
    "d11_staffalert_summary_gangdealer": "A Dealer has been discovered you have been awarded $500",
    "d11_staffalert_summary_making_move": "We've got information that a Gang is making a move.",
    "d11_staffalert_title_AdvancedFarming01": "Automatic Crop Planting",
    "d11_staffalert_title_AdvancedFarming02": "Crop Distribution",
    "d11_staffalert_title_AdvancedFarming03": "The Fertilizer System",
    "d11_staffalert_title_ArmouryPlaced": "Stun Batons",
    "d11_staffalert_title_BasicFarming01": "The Farming System",
    "d11_staffalert_title_BasicFarming02": "Farmers",
    "d11_staffalert_title_BasicFarming03": "Fruit Trees",
    "d11_staffalert_title_BountyHunter": "The Prison is being overwhelmed, we need some help handling the undead, fast.",
    "d11_staffalert_title_CELLS01": "The prison is not running at maximum capacity.",
    "d11_staffalert_title_CONTRABAND01": "The supply of tools and weapons in the prison is dangerously high.",
    "d11_staffalert_title_CONTRABAND02": "The supply of narcotics in the prison is dangerously high.",
    "d11_staffalert_title_CONTRABAND03": "Large amounts of contraband found.",
    "d11_staffalert_title_CalamityHeatwave01": "Heatwave",
    "d11_staffalert_title_DEATHROW01": "Consider adding a Death Row to the prison.",
    "d11_staffalert_title_DOCTOR01": "Nobody is working in the Infirmary.",
    "d11_staffalert_title_DeepFreeze01": "Deep Freeze",
    "d11_staffalert_title_GreenEnergy01": "Green Energy Production",
    "d11_staffalert_title_GreenEnergy02": "Transforming Green Energy",
    "d11_staffalert_title_GreenEnergy03": "Exporting Stored Power",
    "d11_staffalert_title_HOLDINGCELL01": "Too many prisoners are being held in Holding Cells.",
    "d11_staffalert_title_INFORMANTS01": "An informant is in grave danger.",
    "d11_staffalert_title_LightningStorm01": "Lightning Storm",
    "d11_staffalert_title_MONEY01": "The prison is running out of money.",
    "d11_staffalert_title_MysteryCrate": "Fell off the back.",
    "d11_staffalert_title_NEEDS01": "Too many prisoners are complaining about a lack of toilets.",
    "d11_staffalert_title_NEEDS02": "Too many prisoners are complaining about a lack of toilets.",
    "d11_staffalert_title_NEEDS03": "Too many prisoners are complaining about a lack of sleep.",
    "d11_staffalert_title_NEEDS04": "Too many prisoners are complaining of hunger.",
    "d11_staffalert_title_NEEDS05": "The number of prisoners missing their families is at a dangerous level.",
    "d11_staffalert_title_NEEDS06": "The prison desperately needs cleaning.",
    "d11_staffalert_title_NEEDS07": "Our prisoners don't feel safe here.",
    "d11_staffalert_title_NEEDS08": "Our prisoners aren't very clean.",
    "d11_staffalert_title_NEEDS09": "Our prisoners need exercise.",
    "d11_staffalert_title_NEEDS10": "Prisoners are so bored they're going stir crazy.",
    "d11_staffalert_title_NEEDS11": "Prisoners need somewhere to sit during Free Time.",
    "d11_staffalert_title_NEEDS12": "Our prisoners want some privacy.",
    "d11_staffalert_title_NEEDS13": "Our prisoners need Free Time to keep them calm.",
    "d11_staffalert_title_NEEDS14": "Our prisoners need access to clean clothes.",
    "d11_staffalert_title_NEEDS15": "Control the levels of drug addiction in your prison.",
    "d11_staffalert_title_NEEDS16": "Control the levels of alcohol addiction in your prison.",
    "d11_staffalert_title_NEEDS18": "Spiritual guidance has a calming effect on prisoners.",
    "d11_staffalert_title_NEEDS19": "Our prisoners lack basic literacy skills.",
    "d11_staffalert_title_OBJECTS01": "We are not equipped to handle a fire in the prison.",
    "d11_staffalert_title_OBJECTS02": "The prison is not efficiently disposing of waste.",
    "d11_staffalert_title_OBJECTS03": "The prison is missing a comprehensive CCTV system.",
    "d11_staffalert_title_OBJECTS04": "The prison is missing a Door Control system.",
    "d11_staffalert_title_POWER01": "Areas of the Prison are without power.",
    "d11_staffalert_title_POWER02": "One of our Power Stations is overloaded.",
    "d11_staffalert_title_PRISONERS02": "The Guards are outnumbered.",
    "d11_staffalert_title_PRISONERS03": "The quality of our cells is too low.",
    "d11_staffalert_title_ROOMS01": "A room in your prison does not meet the required criteria.",
    "d11_staffalert_title_RatInfestationLevel01": "Rat Infestation",
    "d11_staffalert_title_STAFF01": "The majority of your staff are exhausted.",
    "d11_staffalert_title_ShortCircuit": "The Backup Generator has short-circuited.",
    "d11_staffalert_title_WATER01": "Areas of the prison are without running water.",
    "d11_staffalert_title_WeatherDetected": "Severe weather Detected",
    "d11_staffalert_title_granterror": "Grant Error",
    "d11_staffalert_title_making_move": "Gang is making a move.",
    "d11_staffalert_tooltip_AdvancedFarming01": "Open Policies [[*X]]",
    "d11_staffalert_tooltip_AdvancedFarming02": "Open Logistics [[*X]]",
    "d11_staffalert_tooltip_AdvancedFarming03": "Open Objects [[*X]]",
    "d11_staffalert_tooltip_BasicFarming01": "Open Room [[*X]]",
    "d11_staffalert_tooltip_BasicFarming02": "Open Hire Staff [[*X]]",
    "d11_staffalert_tooltip_BasicFarming03": "Open Objects [[*X]]",
    "d11_staffalert_tooltip_CELLS01": "Increase Prisoner Intake [[*X]]",
    "d11_staffalert_tooltip_CONTRABAND01": "Build Metal Detectors [[*X]]",
    "d11_staffalert_tooltip_CONTRABAND02": "Hire Dog Handlers [[*X]]",
    "d11_staffalert_tooltip_CONTRABAND03": "View Intelligence Report [[*X]]",
    "d11_staffalert_tooltip_DEATHROW01a": "Build a Death Row [[*X]]",
    "d11_staffalert_tooltip_DEATHROW01b": "Research Death Row [[*X]]",
    "d11_staffalert_tooltip_DOCTOR01": "Hire Doctors [[*X]]",
    "d11_staffalert_tooltip_GreenEnergy01": "Open Utility/Electrical [[*X]]",
    "d11_staffalert_tooltip_GreenEnergy02": "Open Utility/Electrical [[*X]]",
    "d11_staffalert_tooltip_GreenEnergy03": "Open Wiring [[*X]]",
    "d11_staffalert_tooltip_HOLDINGCELL01": "Build More Cells [[*X]]",
    "d11_staffalert_tooltip_INFORMANTS01": "Change to Protective Custody [[*X]]",
    "d11_staffalert_tooltip_MONEY01": "Accept a new Grant [[*X]]",
    "d11_staffalert_tooltip_NEEDS01": "Add more toilets [[*X]]",
    "d11_staffalert_tooltip_NEEDS02": "Add more toilets [[*X]]",
    "d11_staffalert_tooltip_NEEDS03": "Modify Regime [[*X]]",
    "d11_staffalert_tooltip_NEEDS04": "Hire Cooks [[*X]]",
    "d11_staffalert_tooltip_NEEDS05": "Build Phone Booths [[*X]]",
    "d11_staffalert_tooltip_NEEDS06": "Hire Janitors [[*X]]",
    "d11_staffalert_tooltip_NEEDS07": "View Prisoner Needs [[*X]]",
    "d11_staffalert_tooltip_NEEDS08": "Modify Regime [[*X]]",
    "d11_staffalert_tooltip_NEEDS09": "Build Weights Bench [[*X]]",
    "d11_staffalert_tooltip_NEEDS10": "Build Radio [[*X]]",
    "d11_staffalert_tooltip_NEEDS11": "Build Bench [[*X]]",
    "d11_staffalert_tooltip_NEEDS12": "Create More Cells [[*X]]",
    "d11_staffalert_tooltip_NEEDS13": "Modify Regime [[*X]]",
    "d11_staffalert_tooltip_NEEDS14": "Build a Laundry [[*X]]",
    "d11_staffalert_tooltip_NEEDS15": "Start Pharmacological Therapy [[*X]]",
    "d11_staffalert_tooltip_NEEDS16": "Start Alcoholic Group Therapy [[*X]]",
    "d11_staffalert_tooltip_NEEDS18": "Start a Spiritual Guidance program [[*X]]",
    "d11_staffalert_tooltip_NEEDS19": "Build a Library [[*X]]",
    "d11_staffalert_tooltip_OBJECTS01": "Build Sprinklers [[*X]]",
    "d11_staffalert_tooltip_OBJECTS02": "Build Bins [[*X]]",
    "d11_staffalert_tooltip_OBJECTS03": "Build CCTV Cameras [[*X]]",
    "d11_staffalert_tooltip_OBJECTS04": "Build Door Control system [[*X]]",
    "d11_staffalert_tooltip_POWER01": "Build Electrical Cables [[*X]]",
    "d11_staffalert_tooltip_POWER02": "Increase Power Supply [[*X]]",
    "d11_staffalert_tooltip_PRISONERS02": "Hire Guards [[*X]]",
    "d11_staffalert_tooltip_PRISONERS03": "Improve Cells [[*X]]",
    "d11_staffalert_tooltip_ROOMS01": "Check Requirements [[*X]]",
    "d11_staffalert_tooltip_STAFF01": "Build a Staff Room [[*X]]",
    "d11_staffalert_tooltip_WATER01": "Build Water Pipes [[*X]]",
    "d11_staffalert_urgentsummary_CELLS01": "We have lots of spare room to take in more prisoners!",
    "d11_staffalert_urgentsummary_CONTRABAND01": "The availability of tools and weapons in your prison is dangerous!",
    "d11_staffalert_urgentsummary_CONTRABAND02": "The availability of narcotics in your prison is dangerous!",
    "d11_staffalert_urgentsummary_CONTRABAND03": "The levels of contraband in the prison are out of control!",
    "d11_staffalert_urgentsummary_DEATHROW01": "We could make a lots of money quickly if we added a Death Row to the prison.",
    "d11_staffalert_urgentsummary_DOCTOR01": "We need to hire Doctors to work in our Infirmary!",
    "d11_staffalert_urgentsummary_HOLDINGCELL01": "We must reduce the number of prisoners in our Holding Cells!",
    "d11_staffalert_urgentsummary_INFORMANTS01": "One of our informants is about to be discovered, his life is in danger!",
    "d11_staffalert_urgentsummary_MONEY01": "We are running seriously low on cash!",
    "d11_staffalert_urgentsummary_NEEDS01": "Seriously! I'm not joking. Build more toilets!",
    "d11_staffalert_urgentsummary_NEEDS02": "Seriously! I'm not joking. Build more toilets!",
    "d11_staffalert_urgentsummary_NEEDS03": "Hey! Wake up! Your prisoners need sleep!",
    "d11_staffalert_urgentsummary_NEEDS04": "Put that cookie down! Our prisoners are starving!",
    "d11_staffalert_urgentsummary_NEEDS05": "Have a heart...you must allow our prisoners to contact their families!",
    "d11_staffalert_urgentsummary_NEEDS06": "Yuk! Our prison is disgusting.",
    "d11_staffalert_urgentsummary_NEEDS07": "Our prisoners don't feel safe here. Please, do something.",
    "d11_staffalert_urgentsummary_NEEDS08": "Eww, our prisoners are filthy.",
    "d11_staffalert_urgentsummary_NEEDS09": "Oh dear, our prisoners are very unhealthy.",
    "d11_staffalert_urgentsummary_NEEDS10": "Our prisoners are bored out of their skulls!",
    "d11_staffalert_urgentsummary_NEEDS11": "Oh come on, all they want is somewhere to sit.",
    "d11_staffalert_urgentsummary_NEEDS12": "Our prisoners are getting angry, you wouldn't like them when they're angry.",
    "d11_staffalert_urgentsummary_NEEDS13": "They're not drones you know, they need Free Time to keep them going!",
    "d11_staffalert_urgentsummary_NEEDS14": "Goodness me! We have a prison full of ragamuffins!",
    "d11_staffalert_urgentsummary_NEEDS15": "Far too many of our prisoners are addicted to drugs. We must do something!",
    "d11_staffalert_urgentsummary_NEEDS16": "Our prisoners have a serious drinking problem!",
    "d11_staffalert_urgentsummary_NEEDS18": "Our prisoners are demanding spiritual guidance.",
    "d11_staffalert_urgentsummary_NEEDS19": "We should make a room for prisoners who can't read good.",
    "d11_staffalert_urgentsummary_OBJECTS01": "We are seriously at risk if a fire breaks out!",
    "d11_staffalert_urgentsummary_OBJECTS02": "We really need to buy some bins!",
    "d11_staffalert_urgentsummary_OBJECTS03": "We really need to install more CCTV Cameras!",
    "d11_staffalert_urgentsummary_OBJECTS04": "It's time we increase efficiency and install a Door Control system!",
    "d11_staffalert_urgentsummary_POWER01": "Some areas of the Prison are still without power!",
    "d11_staffalert_urgentsummary_POWER02": "Your Power Station is seriously overloaded!",
    "d11_staffalert_urgentsummary_PRISONERS02": "Our Guards are outnumbered, you must hire more Guards!",
    "d11_staffalert_urgentsummary_PRISONERS03": "The general quality of our cells needs to be improved as soon as possible!",
    "d11_staffalert_urgentsummary_ROOMS01": "Some of your rooms are still invalid!",
    "d11_staffalert_urgentsummary_STAFF01": "Your staff are exhausted, you must help them!",
    "d11_staffalert_urgentsummary_WATER01": "Some areas of the Prison are still without water!",
    "event_rat_illnessWarning_advisor": "The rat problem is now an infestation. If their numbers aren't reduced, it's only a matter of time before they pass on disease to the prisoners.",
    "execution_warning_one": "Should the next execution performed here not follow the correct procedure, you will be fired from your position.",
    "execution_warning_two": "Due to your past failures to follow correct procedure, one more breach of protocol in this manner will result in you being fired from your position.",
    "ferry_warning": "Departure Blocked",
    "help_warning_deathrow": "Our first Death Row prisoner has just arrived. We'll need to make sure we have a Death Row Appeal program set up in a Parole Room, so that they can have their appeal hearings.",
    "help_warning_gangleader": "The leader of one of the gangs in the prison is currently being punished. It's your choice how to proceed, but all of their gang members are going to cause a lot of trouble while the punishment is in place.",
    "help_warning_prisonerreleased": "Reform Programs are key to prisoners successfully reintegrating into society. Some offenders will start successful new lives whilst others fall back into old ones and reoffend. Reformed prisoners will bring an additional cash reward but some prisoners who reoffend could return to your prison. Not only will you incur a fine for their failed rehabilitation, but they may also have picked up additional bad habits whilst on the outside.",
    "roomerror_deathrow_sharedcell": "Death Row Prisoners require individual cells, and cannot be assigned to shared housing",
    "roomerror_laundryoverloaded": "Laundry Baskets are unable to be unloaded. The Laundry may be too small to meet the demand.",
    "roomerror_nocanteen_cells": "There are no canteens accessible by this cell. Prisoners in this cell will have nowhere to eat",
    "roomerror_nocanteen_kitchen": "There are no canteens accessible by this kitchen. It will not cook any food for meal time",
    "roomerror_nodeliveryarealinked": "There is no Delivery area linked to this, in Logistics.",
    "roomerror_nokitchen": "There are no kitchens capable of sending food to this canteen",
    "roomerror_nonursery": "There are no nurseries accessible by this cell. Family Cells require a nursery for the prisoners to eat in",
    "roomerror_noprisoners": "There are no prisoners assigned to eat at this canteen",
    "score_tooltip_clemencywarning": "The chance of this prisoner being granted clemency is currently above the State Approved safe level. If you proceed with this execution, you will be held personally responsible if it is later found he would have been granted clemency.",
    "victory_adviserwarning_UndeadEscapes1": "I just saw some 'escapees'...you need to stop letting these...these things...leave the grounds of the prison. There's no telling what will happen if more of them escape.",
    "victory_adviserwarning_bankrupt1": "We are bankrupt! Your disastrous management has led us to financial ruin.",
    "victory_adviserwarning_bankrupt2": "Find a way to fix this soon or you will be fired.",
    "victory_adviserwarning_executions1": "This is the second time that you have put an innocent prisoner to death. The public outrage is enormous.",
    "victory_adviserwarning_executions2": "If another innocent prisoner is executed, you will be held responsible.",
    "victory_adviserwarning_insaneprisonersdeaths1": "We can't continue to let our criminally insane inmates suffer abuse within our prison! The media will drag our name through the mud if we don't get our act together!",
    "victory_adviserwarning_reoffenders1": "A lot of the prisoners you have put up for early release have gone on to commit new crimes. This could cost us if we don't take control of the situation.",
    "victory_adviserwarning_reoffenders2": "If too many more prisoners reoffend upon release, you'll be the one to take the blame.",
    "victory_adviserwarning_riot1": "Your prison is out of control. Put down this riot now, or the government will step in and retake the prison by force.",
    "victory_adviserwarning_staffpayrise1": "Our staff have become unhappy with their working conditions in the prison and have threatened to go on strike if they don't get a 50% pay rise.",
    "victory_adviserwarning_staffstrike1": "Our staff have gone on strike! They will still be willing to return if they get their 50% pay rise.",
    "victory_adviserwarning_toomanydeaths1": "Yesterday was a very dark chapter in the history of this prison. Far too many people lost their lives here.",
    "victory_adviserwarning_toomanydeaths2": "Make sure nobody else dies today, or you will face prosecution for criminal negligence.",
    "victory_adviserwarning_toomanyescapes1": "We have a PR disaster brewing here. Far too many prisoners have escaped recently, and it's your fault.",
    "victory_adviserwarning_toomanyescapes2": "Lock this place down and make sure nobody else escapes, otherwise the press will expect your head on a platter.",
    "victory_adviserwarning_wardendeaths1": "Working for you has become much too hazardous. We're struggling to find wardens who want to work at the prison.",
    "victory_adviserwarning_wardendeaths2": "If you let another warden die, we will have no choice but to fire you.",
    "victory_warning": "WARNING",
    "victory_warning_UndeadEscapes": "You will be held accountable for this",
    "victory_warning_bankrupt": "You have 24 hours to avert financial disaster.",
    "victory_warning_executions": "You will be fired if another innocent prisoner is executed.",
    "victory_warning_insaneprisonersabused": "You will be fired if too many insane inmates are attacked by guards.",
    "victory_warning_insaneprisonersdeaths": "You will be fired if too many insane inmates die.",
    "victory_warning_riot": "End this riot soon, or our government will be forced to assume control.",
    "victory_warning_staffonstrike": "The staff have gone on strike - we've lost about 90% of our guard force! If we don't increase their pay with a day, lots of them are threatening to quit entirely.",
    "victory_warning_staffpayrise": "Your staff will go on strike if their pay isn't increased.",
    "victory_warning_staffstrike": "Your staff are on strike!",
    "victory_warning_toomanydeaths": "You face prosecution if too many more deaths occur today.",
    "victory_warning_toomanyescapes": "You will be fired if too many more escapes occur today.",
    "wardenmode_combatwarning": "SELF DEFENCE UNAUTHORISED",
    "wardenmode_combatwarning_caption": "You must not harm prisoners unless acting in self defence",
    "weather_warning_title": "Weather Warning Issued",
}
