"""Build ``src/protocol/room_rules.py`` from the game's ``materials*.txt`` (``BEGIN Room``).

Run as ``python -m src.protocol.roomgen "<data dir>"`` (the folder with ``materials.txt``
and ``materials_dlc.txt``). Each room block lists ``Requirement`` lines::

    BEGIN Requirement Type MinimumSize  x 4  y 4  END
    BEGIN Requirement Type Object  Id Table  Alt SmallTable,OakTable  END
    BEGIN Requirement Type Indoor  END            (also Enclosed, Secure, Outdoor, AdjacentObject)

Later files add rooms; a room defined twice keeps its last definition.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DATA_FILES = ("materials.txt", "materials_dlc.txt")
OUT_PATH = Path(__file__).with_name("room_rules.py")
HEADER = '''"""Room requirements from the game's ``data/materials*.txt`` (``BEGIN Room``).

Generated by ``python -m src.protocol.roomgen``: each room's minimum size, flags
(``Enclosed`` walls all round, ``Indoor`` floor under a roof, ``Secure`` fenced from the
outside, ``Outdoor``, ``AdjacentObject``) and required objects (any of the object or its
alternatives). A room that misses one is flagged in the game and its grant objective
(``RequirementsMet``) stays open.
"""

from __future__ import annotations

ROOM_RULES: dict[
    str,
    tuple[
        tuple[int, int] | None, tuple[str, ...], tuple[tuple[str, tuple[str, ...]], ...]
    ],
] = {
'''
FOOTER = '''}


def describe(room: str) -> str | None:
    """One line of what ``room`` needs, or None for an unknown room."""
    rule = ROOM_RULES.get(room)
    if rule is None:
        return None
    size, flags, objs = rule
    parts = [f"at least {size[0]}x{size[1]}"] if size else []
    parts += [f.lower() for f in flags]
    parts += [o + (f" (or {', '.join(a)})" if a else "") for o, a in objs]
    return f"{room}: " + ("; ".join(parts) or "no requirements")
'''
_REQUIREMENT = re.compile(r"BEGIN Requirement\s+(.*?)\s+END", re.S)
_FLAGS = ("Enclosed", "Indoor", "Secure", "Outdoor", "AdjacentObject")


def parse_rooms(text: str) -> dict[str, tuple]:
    """Room name -> (min size or None, flags, ((object, alternatives), ...))."""
    out: dict[str, tuple] = {}
    for block in re.split(r"\nBEGIN Room\b", "\n" + text)[1:]:
        name = re.search(r"\n?\s*Name\s+(\w+)", block)
        if name is None:
            continue
        size = None
        flags: list[str] = []
        objects: list[tuple[str, tuple[str, ...]]] = []
        for req in _REQUIREMENT.findall(block.split("\nEND", 1)[0] if False else block):
            words = req.split()
            if not words or words[0] != "Type":
                continue
            kind = words[1] if len(words) > 1 else ""
            if kind == "MinimumSize":
                x = int(words[words.index("x") + 1])
                y = int(words[words.index("y") + 1])
                size = (x, y)
            elif kind in _FLAGS:
                flags.append(kind)
            elif kind == "Object" and "Id" in words:
                ident = words[words.index("Id") + 1]
                alts: tuple[str, ...] = ()
                if "Alt" in words:
                    alts = tuple(
                        a for a in words[words.index("Alt") + 1].split(",") if a
                    )
                objects.append((ident, alts))
        out[name[1]] = (size, tuple(flags), tuple(objects))
    return out


def render(rooms: dict[str, tuple]) -> str:
    lines = [HEADER]
    for name, (size, flags, objects) in rooms.items():
        lines.append(
            f"    {name!r}: ({size!r}, {flags!r}, {objects!r}),\n".replace("'", '"')
        )
    lines.append(FOOTER)
    return "".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    rooms: dict[str, tuple] = {}
    for name in DATA_FILES:
        path = Path(argv[1]) / name
        if path.exists():
            rooms.update(parse_rooms(path.read_text(encoding="utf-8", errors="ignore")))
    OUT_PATH.write_text(render(rooms), encoding="utf-8")
    print(f"{len(rooms)} rooms -> {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
