"""Prison Architect RPC table: wire event code -> name and argument types.

Generated from the game binary (``Prison Architect64.exe``, IDA 9.0 database):
the names come from the RPC name table initialiser (``RPC::initNames?``,
``0x140030E20``), the argument types from the ``RPC<...>`` template
instantiation each id is registered with. Do not edit by hand; regenerate
from ``journal/journal2.md`` (see "The RPC table").

Type names are the game's C++ types: ``int``, ``bool``, ``float``,
``string``, ``signed char``, ``ObjectId``, ``Vector2``, ``Vector3``,
``WorldPosition``, ``MemoryBlock``, ``MisconductPolicy``, ``SoundConstraint``,
``SoundObjectId``, ``NetworkSoundId``, ``CustomSectorNetworkData``. How the
composite ones flatten into wire values is *not* fully known (see
``COMPOSITE_ARITY`` in ``src/protocol/rpc.py``).
"""

RPCS: dict[int, tuple[str, tuple[str, ...]]] = {
    0: ("None", ()),
    1: ("SetNumSaveDataChunks", ("int", "int")),
    2: ("SaveDataChunkAck", ()),
    3: ("SaveDataChunk", ("MemoryBlock",)),
    4: ("ProcessingStarted", ()),
    5: ("AuthoriseConnection", ("string",)),
    6: ("KickPlayer", ()),
    7: ("IncorrectPassword", ()),
    8: ("SendingSaveGame", ()),
    9: ("DirectoryData", ("string", "MemoryBlock")),
    10: ("LandPurchased", ()),
    11: ("LogObjectsFromIndex", ("int",)),
    12: ("FirstQueued", ()),
    13: ("ObjectAdded", ("ObjectId", "int")),
    14: ("ObjectRemoved", ("ObjectId",)),
    15: ("CreateRoom", ("ObjectId", "int")),
    16: ("RemoveRoom", ("ObjectId",)),
    17: ("PowerCellModified", ("int", "int", "int")),
    18: ("WaterCellModified", ("int", "int", "int", "bool")),
    19: ("WaterCellCleared", ("int", "int", "bool")),
    20: ("RPCWaterValveChanged", ("int", "int", "bool")),
    21: ("ObjectiveRemoved", ("string", "bool")),
    22: ("MarkerCreatedId", ("ObjectId", "int")),
    23: ("MarkerCreatedPos", ("WorldPosition", "int")),
    24: ("SectorZoneChange", ("int", "int", "CustomSectorNetworkData")),
    25: ("GangSegregationChange", ("int", "int")),
    26: ("SectorAccessOnlyChange", ("int", "bool")),
    27: ("SectorJobCountChange", ("int", "int")),
    28: ("SectorAddTarget", ("int", "int")),
    29: ("SectorClearTargets", ("int",)),
    30: ("ChosenScheduleChange", ("int", "int")),
    31: ("GuardDeploymentChange", ("int", "int", "int", "int")),
    32: ("PlanningJobChange", ("int", "int", "int", "int", "Vector2", "int", "int")),
    33: ("PlayerSetsTarget", ("int", "Vector2", "bool", "ObjectId")),
    34: ("ElectricalSwitch", ("int", "bool")),
    35: ("PerformAction", ("ObjectId", "int")),
    36: ("BeginResearch", ("int",)),
    37: ("ToggleResearchDesired", ("int",)),
    38: ("ApplyPrisonerCategory", ("ObjectId", "int")),
    39: ("ApplyPunishment", ("ObjectId", "int", "int")),
    40: ("ClearAllPunishments", ("ObjectId",)),
    41: ("ActivateInformant", ("ObjectId", "bool")),
    42: ("DeactivateInformant", ("ObjectId", "bool")),
    43: ("NewVehicleCallout", ("int",)),
    44: ("SquadDismissal", ("ObjectId",)),
    45: ("SackStaff", ("ObjectId",)),
    46: ("ApporveTransfer", ("ObjectId",)),
    47: ("AcceptGrant", ("string",)),
    48: ("CancelGrant", ("string",)),
    49: ("IncreaseLoan", ()),
    50: ("DecreaseLoan", ()),
    51: ("SellShares", ("int",)),
    52: ("BuyBackShares", ("int",)),
    53: ("SetRegime", ("int", "int", "int")),
    54: ("EvictGangTerritory", ("ObjectId",)),
    55: ("CrisisButtonClicked", ("int", "int", "bool")),
    56: ("FiremanAimHose", ("ObjectId", "Vector2")),
    57: ("FireInformant", ("ObjectId",)),
    58: ("TransferAllowedChange", ("bool", "int")),
    59: ("TransferChange", ("int", "bool", "int")),
    60: ("TransferAmountChange", ("int", "int", "int")),
    61: ("PolicyChange", ("int", "MisconductPolicy", "int")),
    62: ("PrivilegePolicyChange", ("int", "int", "bool")),
    63: ("MealPolicyChange", ("int", "int", "int")),
    64: ("ParoleRateChange", ("int", "int")),
    65: ("UseCellQualityChange", ("bool",)),
    66: ("StaffPayModifierChange", ("float",)),
    67: ("StaffMaxBreakChange", ("int", "int")),
    68: ("SentencesEnabledChange", ("bool",)),
    69: ("ExtensionCriteriaChange", ("int", "bool")),
    70: ("ExtensionCriteriaValueChange", ("int", "int")),
    71: ("ExtensionCriteriaMetChange", ("int",)),
    72: ("ReductionCriteriaChange", ("int", "bool")),
    73: ("ReductionCriteriaValueChange", ("int", "int")),
    74: ("ReductionCriteriaMetChange", ("int",)),
    75: ("NeedsDistributionUpdate", ("bool", "int")),
    76: ("EntityUpdateRequest", ("ObjectId",)),
    77: ("IntakeRatioChange", ("int", "float")),
    78: ("IntakeTypeChange", ("int",)),
    79: ("IntakeNumTotalChange", ("int",)),
    80: ("IntakeTimeChange", ("int",)),
    81: ("IntakeRestrictionsChange", ("bool",)),
    82: ("StartReformProgram", ("int", "bool")),
    83: ("StopReformProgram", ("int",)),
    84: ("RunReformScheduler", ()),
    85: ("ScheduleProgram", ("int", "int", "int", "ObjectId")),
    86: ("SetProgramManual", ("int", "bool")),
    87: ("LandPurchaseRequest", ("int", "int", "int", "int", "bool", "bool")),
    88: (
        "TriggerSoundEvent",
        ("SoundConstraint", "string", "string", "NetworkSoundId"),
    ),
    89: (
        "TriggerPositionedSoundEvent",
        ("SoundConstraint", "string", "string", "Vector3", "NetworkSoundId"),
    ),
    90: (
        "TriggerObjectSoundEvent",
        ("SoundConstraint", "SoundObjectId", "string", "NetworkSoundId"),
    ),
    91: (
        "TriggerObjectCustomSoundEvent",
        ("SoundConstraint", "SoundObjectId", "string", "string", "NetworkSoundId"),
    ),
    92: ("WiredObjectConnect", ("ObjectId", "ObjectId")),
    93: ("WiredObjectClear", ("ObjectId",)),
    94: ("WireDataRequested", ()),
    95: ("StopAllSounds", ("NetworkSoundId",)),
    96: ("GameSpeedChange", ("int",)),
    97: ("TreeAgeChange", ("ObjectId", "int")),
    98: ("DeliveryStopSetAllowed", ("ObjectId", "int", "bool")),
    99: ("DeliveryStopSetOverall", ("ObjectId", "int", "bool")),
    100: ("DeliveryStopAssignZone", ("ObjectId", "ObjectId", "int")),
    101: ("DeliveryStopClearAllZones", ("ObjectId",)),
    102: ("FarmingPolicy", ("bool", "int", "int", "int", "int", "float")),
    103: ("AddRoomCropDist", ("ObjectId", "ObjectId")),
    104: ("RemoveRoomCropDist", ("ObjectId", "ObjectId")),
    105: ("LockPercentagesCropDist", ("ObjectId", "int", "int")),
    106: ("ChangePercentagesCropDist", ("ObjectId", "int", "int", "float")),
    107: ("RoomConnectionToggled", ("ObjectId", "ObjectId")),
    108: ("LogicCircuitChange", ("ObjectId", "int")),
    109: ("LabourManagementChanged", ("ObjectId", "int", "int")),
    110: ("SpawnObject", ("int", "int", "int", "int", "int")),
    111: ("CoveragePlanChanged", ("int", "bool", "bool")),
    112: ("CoveragePlanEmergencyChanged", ("int", "int", "bool", "int", "int", "int")),
    113: ("WaterCellFrozen", ("int", "int", "bool", "bool")),
    114: ("WaterCellInsulated", ("int", "int", "bool")),
    115: ("WaterCellFlood", ("int", "int", "int", "float")),
    116: ("PrisonerWageChanged", ("int", "float")),
    117: ("NewSpeechAdded", ("int", "string")),
    118: ("TransactionAdded", ("int", "string", "signed char", "string")),
    119: ("TransactionAppended", ("int", "string", "signed char", "string")),
    120: ("CommitBuildPlanning", ("int", "int")),
    121: ("VisitationRateChange", ("int", "int")),
    122: ("IntakeNumPerDayChange", ("int",)),
    123: ("LightningStrike", ("int", "Vector2", "float")),
    124: ("ToggleFogOfWar", ("bool",)),
    125: ("IntakeTogglePrisonerReplacement", ()),
    126: ("RemovePrisoner", ("ObjectId",)),
    127: ("AssignGuardToPrisoner", ("ObjectId",)),
    128: ("UnassignGuardFromPrisoner", ("ObjectId",)),
    129: ("MarkingTypeChanged", ("ObjectId", "int", "int")),
    130: ("RestrictAccessSettingsChanged", ("ObjectId", "bool", "bool")),
    131: ("PrisonerCategoryChanged", ("ObjectId", "int")),
    132: ("QuickCellChange", ("ObjectId", "ObjectId")),
    133: ("CrisisCustomSearchArea", ("int", "int", "bool")),
    134: ("CrisisCustomSaveSchedule", ("int", "int", "int", "int", "int")),
    135: ("RegisterInformant", ("ObjectId",)),
    136: ("ChangeRank", ("ObjectId", "int")),
    137: ("ToggleStaffKeys", ("bool",)),
    138: ("Distortion", ("ObjectId",)),
    139: ("ToggleAllowStunBatons", ("bool",)),
    140: ("ControlAdvancedSearchLight", ("ObjectId",)),
    141: ("AimAdvancedSearchLight", ("ObjectId", "Vector2")),
    142: ("EquipPrisonerTrackingBelt", ("ObjectId",)),
    143: ("LastQueued", ()),
}
"""``id -> (name, argument types)``."""
